### ISSUE TITLE
[OCP-4.X] Are these tasks needed anymore

### ISSUE THREAD

**Issue by akrzos** [openshift-scale/scale-ci-deploy#14]
https://github.com/openshift-scale/scale-ci-deploy/blob/master/OCP-4.X/roles/quickstart/tasks/main.yml#L21-L53

@chaitanyaenr PTAL

**Comment by chaitanyaenr** [comment]
@akrzos they are not needed, will remove them.

**Comment by akrzos** [comment]
Thanks!
