### ISSUE TITLE
patching the monitoring operator does not work

### ISSUE THREAD

**Issue by jtaleric** [openshift-scale/scale-ci-deploy#47]
https://github.com/openshift-scale/scale-ci-deploy/blob/master/OCP-4.X/roles/post-install/tasks/main.yml#L200-L203

Results in 
```
Node-Selectors:  beta.kubernetes.io/os=linux
                 node-role.kubernetes.io/infra=
                 node-role.kubernetes.io/master=

```

Which causes the monitoring operator to fail since there is no node with both labels.

We should be replacing the line, instead of just patching the infra node. 

Maybe this is new for 4.3?

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/scale-ci-deploy/pull/50.
