### ISSUE TITLE
[OCP-4.x] Change pbench role to workload

### ISSUE THREAD

**Issue by akrzos** [openshift-scale/scale-ci-deploy#9]
@chaitanyaenr @jmencak @sjug @ekuric please give me your thoughts.

In my opinion we should rename the `pbench` node to `workload` and not require two node labels (pbench and controller).  The pbench node is used to host running the workload container which orchestrates the pbench agent and pbench collected data and I think having a more consistent name and thus only a single node label will make it a bit easier for others to run/understand the purpose of the workload node.

**Comment by ekuric** [comment]
+1, I agree with this proposal.

**Comment by jmencak** [comment]
Agreed, I don't see any reason why we shouldn't do this.

**Comment by chaitanyaenr** [comment]
+1, I agree that we should rename the pbench node to workload. We just need to make sure the host running the workload has a workload label and the hosts running the pbench-agents should have an pbench_role=agent label to differentiate between the controller and agents and to make sure controller lands on node with workload label.

**Comment by akrzos** [comment]
Fixed with #11
